### ISSUE TITLE
trying to install it in version 8 but getting error

### ISSUE THREAD

**Issue by jacksolutions** [treveradams/openerp-freeswitch-connector#3]
Traceback (most recent call last):
  File "/opt/odoo/odoo-server/openerp/http.py", line 530, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo-server/openerp/http.py", line 567, in dispatch
    result = self._call_function(*_self.params)
  File "/opt/odoo/odoo-server/openerp/http.py", line 303, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/service/model.py", line 113, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/http.py", line 300, in checked_call
    return self.endpoint(_a, *_kw)
  File "/opt/odoo/odoo-server/openerp/http.py", line 796, in __call__
    return self.method(_args, *_kw)
  File "/opt/odoo/odoo-server/openerp/http.py", line 396, in response_wrap
    response = f(_args, *_kw)
  File "/opt/odoo/odoo-server/addons/web/controllers/main.py", line 953, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/odoo-server/addons/web/controllers/main.py", line 941, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/api.py", line 393, in old_api
    result = new_api(recs, _args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/api.py", line 397, in new_api
    result = [method(rec, _args, *_kwargs) for rec in self]
  File "/opt/odoo/odoo-server/openerp/addons/base/module/wizard/base_module_update.py", line 15, in update_module
    self.updated, self.added = self.env['ir.module.module'].update_list()
  File "/opt/odoo/odoo-server/openerp/api.py", line 239, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/api.py", line 462, in new_api
    result = method(self._model, cr, uid, _args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/addons/base/module/module.py", line 654, in update_list
    handler.load_addons()
  File "/opt/odoo/odoo-server/openerp/http.py", line 1298, in load_addons
    m = __import__('openerp.addons.' + module)
  File "/opt/odoo/odoo-server/openerp/modules/module.py", line 80, in load_module
    mod = imp.load_module('openerp.addons.' + module_part, f, path, descr)
  File "/opt/odoo/custom/addons/base_phone/**init**.py", line 22, in <module>
    from . import base_phone
  File "/opt/odoo/custom/addons/base_phone/base_phone.py", line 26, in <module>
    import phonenumbers
ImportError: No module named phonenumbers

**Comment by jacksolutions** [comment]
i have figured it out

**Comment by treveradams** [comment]
On 6/13/2015 6:04 AM, jacksolutions wrote:

> Traceback (most recent call last):
> File "/opt/odoo/odoo-server/openerp/http.py", line 530, in
> /handle_exception
> return super(JsonRequest, self)./handle_exception(exception)
> File "/opt/odoo/odoo-server/openerp/http.py", line 567, in dispatch
> result = self._call_function(_/self.params)
> File "/opt/odoo/odoo-server/openerp/http.py", line 303, in _call_function
> return checked_call(self.db, *args, */kwargs)
> File "/opt/odoo/odoo-server/openerp/service/model.py", line 113, in
> wrapper
> return f(dbname, /args, */kwargs)
> File "/opt/odoo/odoo-server/openerp/http.py", line 300, in checked_call
> return self.endpoint(/a, */kw)
> File "/opt/odoo/odoo-server/openerp/http.py", line 796, in __call//
> return self.method(/args, */kw)
> File "/opt/odoo/odoo-server/openerp/http.py", line 396, in response_wrap
> response = f(/args, */kw)
> File "/opt/odoo/odoo-server/addons/web/controllers/main.py", line 953,
> in call_button
> action = self./call_kw(model, method, args, {})
> File "/opt/odoo/odoo-server/addons/web/controllers/main.py", line 941,
> in /call_kw
> return getattr(request.registry.get(model), method)(request.cr,
> request.uid, /args, */kwargs)
> File "/opt/odoo/odoo-server/openerp/api.py", line 241, in wrapper
> return old_api(self, /args, */kwargs)
> File "/opt/odoo/odoo-server/openerp/api.py", line 393, in old_api
> result = new_api(recs, /args, */kwargs)
> File "/opt/odoo/odoo-server/openerp/api.py", line 397, in new_api
> result = [method(rec, /args, */kwargs) for rec in self]
> File
> "/opt/odoo/odoo-server/openerp/addons/base/module/wizard/base_module_update.py",
> line 15, in update_module
> self.updated, self.added = self.env['ir.module.module'].update_list()
> File "/opt/odoo/odoo-server/openerp/api.py", line 239, in wrapper
> return new_api(self, /args, */kwargs)
> File "/opt/odoo/odoo-server/openerp/api.py", line 462, in new_api
> result = method(self._model, cr, uid, /args, */kwargs)
> File "/opt/odoo/odoo-server/openerp/addons/base/module/module.py",
> line 654, in update_list
> handler.load_addons()
> File "/opt/odoo/odoo-server/openerp/http.py", line 1298, in load_addons
> m = __import//('openerp.addons.' + module)
> File "/opt/odoo/odoo-server/openerp/modules/module.py", line 80, in
> load_module
> mod = imp.load_module('openerp.addons.' + module_part, f, path, descr)
> File "/opt/odoo/custom/addons/base_phone/_init*.py", line 22, in
> from . import base_phone
> File "/opt/odoo/custom/addons/base_phone/base_phone.py", line 26, in
> import phonenumbers
> ImportError: No module named phonenumbers
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/treveradams/openerp-freeswitch-connector/issues/3.
> 
> This module may not work with version 8. I don't have version 8 and
> haven't updated my modules yet.

I may be asking the original authors (who made it for asterisk but are
reworking theirs) for help to merge mine with theirs).

I have been out of communication for a few months and am just not
looking at this again.

Trever
